<?php
/**
 * Sydney suburb data for programmatic landing pages.
 *
 * Each entry drives:
 *   - URL slug (array key)
 *   - Hero copy (name, description)
 *   - Local context paragraph (housing_era, neighborhoods)
 *   - Schema.org GeoCoordinates (lat/lng)
 *   - Service-area schema (postcode, region)
 *
 * Adding a new suburb:
 *   1. Add a new entry below
 *   2. Re-activate the theme (Appearance → Themes → Activate)
 *      This triggers timeless_create_suburb_pages() which auto-creates
 *      pages for each (service × suburb) combo
 *   3. Pages live at /services/{service-slug}/{suburb-slug}/
 *
 * Quality > quantity: each suburb gets unique local context. Don't add
 * suburbs we have nothing real to say about — Google's thin-content filter
 * downranks programmatic landing pages that are 95% identical.
 */

defined( 'ABSPATH' ) || exit;

return array(

    // ─── Greater Western Sydney ─── //
    'parramatta' => array(
        'name'          => 'Parramatta',
        'postcode'      => '2150',
        'region'        => 'Western Sydney',
        'council'       => 'City of Parramatta',
        'distance_km'   => 24,
        'description'   => 'Sydney\'s second CBD with a heavy concentration of 1970s-90s brick walk-up apartments and investor properties.',
        'housing_era'   => '70s-90s brick walk-ups and post-war townhouses',
        'neighborhoods' => array( 'North Parramatta', 'Harris Park', 'Westmead', 'Rosehill' ),
        'lat'           => -33.8136,
        'lng'           => 151.0034,
    ),
    'penrith' => array(
        'name'          => 'Penrith',
        'postcode'      => '2750',
        'region'        => 'Western Sydney',
        'council'       => 'Penrith City Council',
        'distance_km'   => 55,
        'description'   => 'Outer western Sydney with established family homes and a strong rental market across older brick housing stock.',
        'housing_era'   => '70s-2000s family homes and townhouse complexes',
        'neighborhoods' => array( 'South Penrith', 'Cambridge Park', 'Kingswood', 'Werrington' ),
        'lat'           => -33.7510,
        'lng'           => 150.6943,
    ),
    'castle-hill' => array(
        'name'          => 'Castle Hill',
        'postcode'      => '2154',
        'region'        => 'The Hills District',
        'council'       => 'The Hills Shire Council',
        'distance_km'   => 30,
        'description'   => 'The Hills District hub with large family homes from the 90s and 2000s now showing wear in their original bathrooms.',
        'housing_era'   => '90s-2000s detached family homes and townhouses',
        'neighborhoods' => array( 'Cherrybrook', 'West Pennant Hills', 'Glenhaven', 'Norwest' ),
        'lat'           => -33.7327,
        'lng'           => 151.0002,
    ),

    // ─── Northern Suburbs ─── //
    'chatswood' => array(
        'name'          => 'Chatswood',
        'postcode'      => '2067',
        'region'        => 'Lower North Shore',
        'council'       => 'Willoughby City Council',
        'distance_km'   => 10,
        'description'   => 'Upper north shore commercial centre surrounded by large 70s-80s brick walk-ups and increasingly dense newer apartments.',
        'housing_era'   => '70s-80s brick walk-up apartments',
        'neighborhoods' => array( 'Artarmon', 'Willoughby', 'Roseville', 'Lane Cove' ),
        'lat'           => -33.7969,
        'lng'           => 151.1830,
    ),
    'mosman' => array(
        'name'          => 'Mosman',
        'postcode'      => '2088',
        'region'        => 'Lower North Shore',
        'council'       => 'Mosman Council',
        'distance_km'   => 8,
        'description'   => 'Affluent harbourside suburb with heritage homes and original art deco apartments where keeping period features intact matters.',
        'housing_era'   => 'Federation, Art Deco, and 70s walk-up apartments',
        'neighborhoods' => array( 'Beauty Point', 'Spit Junction', 'Cremorne', 'Neutral Bay' ),
        'lat'           => -33.8281,
        'lng'           => 151.2398,
    ),
    'hornsby' => array(
        'name'          => 'Hornsby',
        'postcode'      => '2077',
        'region'        => 'Upper North Shore',
        'council'       => 'Hornsby Shire Council',
        'distance_km'   => 25,
        'description'   => 'Upper north shore family hub with a large stock of 70s-80s brick homes and walk-up apartments due for bathroom updates.',
        'housing_era'   => '70s-80s detached homes and brick walk-ups',
        'neighborhoods' => array( 'Asquith', 'Waitara', 'Wahroonga', 'Thornleigh' ),
        'lat'           => -33.7038,
        'lng'           => 151.0989,
    ),

    // ─── Eastern Suburbs ─── //
    'bondi' => array(
        'name'          => 'Bondi',
        'postcode'      => '2026',
        'region'        => 'Eastern Suburbs',
        'council'       => 'Waverley Council',
        'distance_km'   => 7,
        'description'   => 'Beachside eastern suburb with art deco apartments where salt air accelerates bathroom wear, and renovations are restricted by strata heritage rules.',
        'housing_era'   => 'Art Deco apartments and post-war brick units',
        'neighborhoods' => array( 'Bondi Beach', 'North Bondi', 'Bondi Junction', 'Tamarama' ),
        'lat'           => -33.8915,
        'lng'           => 151.2767,
    ),
    'surry-hills' => array(
        'name'          => 'Surry Hills',
        'postcode'      => '2010',
        'region'        => 'Inner Sydney',
        'council'       => 'City of Sydney',
        'distance_km'   => 3,
        'description'   => 'Inner-city terrace neighbourhood where many original Victorian-era bathrooms have been left untouched in otherwise renovated homes.',
        'housing_era'   => 'Victorian terraces and converted warehouse apartments',
        'neighborhoods' => array( 'Darlinghurst', 'Redfern', 'Waterloo', 'Paddington' ),
        'lat'           => -33.8842,
        'lng'           => 151.2117,
    ),

    // ─── Northern Beaches ─── //
    'manly' => array(
        'name'          => 'Manly',
        'postcode'      => '2095',
        'region'        => 'Northern Beaches',
        'council'       => 'Northern Beaches Council',
        'distance_km'   => 12,
        'description'   => 'Northern Beaches lifestyle suburb where coastal exposure and older apartment stock make resurfacing a frequent owner request.',
        'housing_era'   => '60s-90s walk-up apartments and beachside cottages',
        'neighborhoods' => array( 'Manly Beach', 'Fairlight', 'Balgowlah', 'Seaforth' ),
        'lat'           => -33.7969,
        'lng'           => 151.2849,
    ),

    // ─── Inner West ─── //
    'strathfield' => array(
        'name'          => 'Strathfield',
        'postcode'      => '2135',
        'region'        => 'Inner West',
        'council'       => 'Strathfield Council',
        'distance_km'   => 12,
        'description'   => 'Inner-west hub with a mix of large heritage homes and 70s-80s brick apartment buildings serving a multicultural community.',
        'housing_era'   => 'Federation homes and 70s-80s walk-up apartments',
        'neighborhoods' => array( 'Burwood', 'Homebush', 'Concord', 'Croydon' ),
        'lat'           => -33.8743,
        'lng'           => 151.0911,
    ),

    // ─── ADDED v1.5.2 (2026-08-13) ───────────────────────────────────────────
    // Chosen from REAL enquiry addresses in the CRM (26 located enquiries across
    // 21 suburbs) plus the major hubs whose housing stock actually suits this work:
    // older bathrooms, high rental turnover, and owners who want an alternative to a
    // full renovation. Deliberately NOT the full Sydney suburb list — thin, near
    // identical location pages are what Google treats as doorway pages, and sites
    // have been penalised for as few as 30-40 of them. Every entry below has a real
    // housing-stock reason to exist.

    // ─── Inner West ─── //
    'marrickville' => array(
        'name'          => 'Marrickville',
        'postcode'      => '2204',
        'region'        => 'Inner West',
        'council'       => 'Inner West Council',
        'distance_km'   => 7,
        'description'   => 'Dense inner-west rental market where interwar cottages and post-war brick flats turn over often and agents need bathrooms refreshed between tenancies.',
        'housing_era'   => 'Interwar cottages and post-war red-brick flats',
        'neighborhoods' => array( 'Dulwich Hill', 'Sydenham', 'Petersham', 'Tempe' ),
        'lat'           => -33.9111,
        'lng'           => 151.1547,
    ),
    'newtown' => array(
        'name'          => 'Newtown',
        'postcode'      => '2042',
        'region'        => 'Inner West',
        'council'       => 'Inner West Council',
        'distance_km'   => 5,
        'description'   => 'Victorian terrace belt where bathrooms are small, original and often heritage-constrained, so refinishing beats the disruption of a full strip-out.',
        'housing_era'   => 'Victorian and Federation terraces with compact bathrooms',
        'neighborhoods' => array( 'Enmore', 'Erskineville', 'Camperdown', 'Stanmore' ),
        'lat'           => -33.8983,
        'lng'           => 151.1793,
    ),
    'drummoyne' => array(
        'name'          => 'Drummoyne',
        'postcode'      => '2047',
        'region'        => 'Inner West',
        'council'       => 'City of Canada Bay',
        'distance_km'   => 8,
        'description'   => 'Waterfront inner-west pocket of interwar brick homes and older unit blocks where bathrooms date from the 70s and 80s.',
        'housing_era'   => 'Interwar brick homes and 70s-80s unit blocks',
        'neighborhoods' => array( 'Russell Lea', 'Five Dock', 'Rodd Point', 'Abbotsford' ),
        'lat'           => -33.8523,
        'lng'           => 151.1543,
    ),

    // ─── Inner Sydney ─── //
    'pyrmont' => array(
        'name'          => 'Pyrmont',
        'postcode'      => '2009',
        'region'        => 'Inner Sydney',
        'council'       => 'City of Sydney',
        'distance_km'   => 2,
        'description'   => 'Converted warehouse apartments and 90s developments where bathrooms are original to the conversion and strata rules make demolition impractical.',
        'housing_era'   => 'Warehouse conversions and 90s apartment blocks',
        'neighborhoods' => array( 'Ultimo', 'Glebe', 'Darling Island', 'Jones Bay' ),
        'lat'           => -33.8700,
        'lng'           => 151.1950,
    ),

    // ─── Northern Sydney ─── //
    'ryde' => array(
        'name'          => 'Ryde',
        'postcode'      => '2112',
        'region'        => 'Northern Sydney',
        'council'       => 'City of Ryde',
        'distance_km'   => 13,
        'description'   => 'Large northern suburb with a heavy concentration of 60s-80s red-brick walk-ups held by investors, where a resurfaced bathroom lets a unit re-let quickly.',
        'housing_era'   => '60s-80s red-brick walk-ups and post-war homes',
        'neighborhoods' => array( 'West Ryde', 'Meadowbank', 'Denistone', 'Top Ryde' ),
        'lat'           => -33.8133,
        'lng'           => 151.1053,
    ),
    'epping' => array(
        'name'          => 'Epping',
        'postcode'      => '2121',
        'region'        => 'Northern Sydney',
        'council'       => 'City of Parramatta',
        'distance_km'   => 18,
        'description'   => 'Established northern suburb where post-war family homes sit alongside newer towers, and original bathrooms are common in the older stock.',
        'housing_era'   => 'Post-war brick homes and 80s townhouses',
        'neighborhoods' => array( 'Beecroft', 'Carlingford', 'Eastwood', 'North Epping' ),
        'lat'           => -33.7726,
        'lng'           => 151.0817,
    ),
    'rhodes' => array(
        'name'          => 'Rhodes',
        'postcode'      => '2138',
        'region'        => 'Northern Sydney',
        'council'       => 'City of Canada Bay',
        'distance_km'   => 16,
        'description'   => 'High-density waterfront apartments with a fast rental turnover, where owners refresh bathrooms between tenants rather than renovate a strata bathroom.',
        'housing_era'   => '2000s high-rise apartments',
        'neighborhoods' => array( 'Liberty Grove', 'Concord West', 'Wentworth Point', 'Homebush Bay' ),
        'lat'           => -33.8300,
        'lng'           => 151.0870,
    ),

    // ─── Eastern Suburbs ─── //
    'randwick' => array(
        'name'          => 'Randwick',
        'postcode'      => '2031',
        'region'        => 'Eastern Suburbs',
        'council'       => 'Randwick City Council',
        'distance_km'   => 7,
        'description'   => 'Eastern-suburbs rental belt of art deco and 60s-70s unit blocks near the hospitals and university, with constant tenant turnover.',
        'housing_era'   => 'Art deco and 60s-70s apartment blocks',
        'neighborhoods' => array( 'Coogee', 'Kensington', 'Queens Park', 'Clovelly' ),
        'lat'           => -33.9145,
        'lng'           => 151.2417,
    ),

    // ─── Southern Sydney ─── //
    'hurstville' => array(
        'name'          => 'Hurstville',
        'postcode'      => '2220',
        'region'        => 'Southern Sydney',
        'council'       => 'Georges River Council',
        'distance_km'   => 16,
        'description'   => 'Southern hub with a large stock of 70s-90s walk-up apartments and investor-held units where full renovation rarely stacks up.',
        'housing_era'   => '70s-90s walk-up apartments and post-war homes',
        'neighborhoods' => array( 'Kogarah', 'Beverly Hills', 'Penshurst', 'Carlton' ),
        'lat'           => -33.9675,
        'lng'           => 151.1027,
    ),
    'sutherland' => array(
        'name'          => 'Sutherland',
        'postcode'      => '2232',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 26,
        'description'   => 'Shire hub of post-war brick homes and older unit blocks where owners tend to hold long and update in stages rather than all at once.',
        'housing_era'   => 'Post-war brick homes and 70s-80s units',
        'neighborhoods' => array( 'Bonnet Bay', 'Jannali', 'Kirrawee', 'Como' ),
        'lat'           => -34.0316,
        'lng'           => 151.0576,
    ),

    // ─── South West Sydney ─── //
    'liverpool' => array(
        'name'          => 'Liverpool',
        'postcode'      => '2170',
        'region'        => 'South West Sydney',
        'council'       => 'Liverpool City Council',
        'distance_km'   => 32,
        'description'   => 'Major south-west centre with extensive post-war housing and investor units, where budget-conscious owners want a bathroom fixed rather than replaced.',
        'housing_era'   => 'Post-war brick homes and 70s-80s units',
        'neighborhoods' => array( 'Lurnea', 'Casula', 'Moorebank', 'Warwick Farm' ),
        'lat'           => -33.9203,
        'lng'           => 150.9236,
    ),
    'bankstown' => array(
        'name'          => 'Bankstown',
        'postcode'      => '2200',
        'region'        => 'South West Sydney',
        'council'       => 'Canterbury-Bankstown Council',
        'distance_km'   => 22,
        'description'   => 'Long-established south-west suburb where post-war homes and older walk-ups still carry their original coloured tiles and baths.',
        'housing_era'   => 'Post-war homes with original 60s-70s bathrooms',
        'neighborhoods' => array( 'Punchbowl', 'Yagoona', 'Condell Park', 'Greenacre' ),
        'lat'           => -33.9171,
        'lng'           => 151.0345,
    ),
    'cabramatta' => array(
        'name'          => 'Cabramatta',
        'postcode'      => '2166',
        'region'        => 'South West Sydney',
        'council'       => 'Fairfield City Council',
        'distance_km'   => 30,
        'description'   => 'South-west centre with a large stock of post-war homes and townhouses, often owner-occupied long term with bathrooms well past their original finish.',
        'housing_era'   => 'Post-war homes and 80s townhouses',
        'neighborhoods' => array( 'Canley Vale', 'Canley Heights', 'Lansvale', 'Fairfield' ),
        'lat'           => -33.8948,
        'lng'           => 150.9356,
    ),

    // ─── Western Sydney ─── //
    'blacktown' => array(
        'name'          => 'Blacktown',
        'postcode'      => '2148',
        'region'        => 'Western Sydney',
        'council'       => 'Blacktown City Council',
        'distance_km'   => 35,
        'description'   => 'Large western centre of post-war and 80s project homes where a resurfaced bathroom is a fraction of a full renovation.',
        'housing_era'   => 'Post-war and 80s project homes',
        'neighborhoods' => array( 'Seven Hills', 'Prospect', 'Kings Langley', 'Doonside' ),
        'lat'           => -33.7688,
        'lng'           => 150.9063,
    ),

    // ─── ADDED v1.5.2 ─── Coverage matched to the best-ranking AU trades sites,
    // filtered to the areas we ACTUALLY service (their list includes regional NSW
    // towns we would have to decline). Every entry carries its own housing-stock
    // reason to exist: several are newer estates where the honest angle is rental
    // turnover, not age.

    'caringbah' => array(
        'name'          => 'Caringbah',
        'postcode'      => '2229',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 24,
        'description'   => 'Shire suburb of post-war brick homes and 70s-80s unit blocks, where owners tend to update a bathroom rather than move.',
        'housing_era'   => 'Post-war brick homes and 70s-80s units',
        'neighborhoods' => array( 'Miranda', 'Woolooware', 'Lilli Pilli', 'Dolans Bay' ),
        'lat'           => -34.0432,
        'lng'           => 151.122,
    ),
    'cronulla' => array(
        'name'          => 'Cronulla',
        'postcode'      => '2230',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 26,
        'description'   => 'Beachside Shire suburb where salt air is hard on bathrooms and much of the housing is older walk-up apartments.',
        'housing_era'   => '60s-80s beachside walk-ups and brick cottages',
        'neighborhoods' => array( 'Woolooware', 'Burraneer', 'Bundeena', 'Greenhills Beach' ),
        'lat'           => -34.0561,
        'lng'           => 151.1523,
    ),
    'illawong' => array(
        'name'          => 'Illawong',
        'postcode'      => '2234',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 28,
        'description'   => 'Quiet Shire pocket of 80s and 90s family homes now reaching the age where original bathrooms start to show.',
        'housing_era'   => '80s-90s brick family homes',
        'neighborhoods' => array( 'Alfords Point', 'Menai', 'Bangor', 'Barden Ridge' ),
        'lat'           => -34.0106,
        'lng'           => 151.029,
    ),
    'bangor' => array(
        'name'          => 'Bangor',
        'postcode'      => '2234',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 29,
        'description'   => 'Established Shire suburb built out through the 80s, so most bathrooms here are original to the house.',
        'housing_era'   => '80s brick and clad family homes',
        'neighborhoods' => array( 'Menai', 'Illawong', 'Barden Ridge', 'Lucas Heights' ),
        'lat'           => -34.0175,
        'lng'           => 151.0281,
    ),
    'yarrawarrah' => array(
        'name'          => 'Yarrawarrah',
        'postcode'      => '2233',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 31,
        'description'   => 'Small Shire suburb of 70s and 80s homes bordering the national park, largely owner-occupied and long held.',
        'housing_era'   => '70s-80s brick family homes',
        'neighborhoods' => array( 'Engadine', 'Loftus', 'Woronora Heights', 'Heathcote' ),
        'lat'           => -34.0561,
        'lng'           => 151.0281,
    ),
    'taren-point' => array(
        'name'          => 'Taren Point',
        'postcode'      => '2229',
        'region'        => 'Sutherland Shire',
        'council'       => 'Sutherland Shire Council',
        'distance_km'   => 23,
        'description'   => 'Mixed residential and light-industrial pocket where the housing is post-war and the rental share is high.',
        'housing_era'   => 'Post-war brick homes and small unit blocks',
        'neighborhoods' => array( 'Sylvania', 'Caringbah', 'Sans Souci', 'Kurnell' ),
        'lat'           => -34.0186,
        'lng'           => 151.113,
    ),
    'maroubra' => array(
        'name'          => 'Maroubra',
        'postcode'      => '2035',
        'region'        => 'Eastern Suburbs',
        'council'       => 'Randwick City Council',
        'distance_km'   => 9,
        'description'   => 'Eastern-suburbs coastal belt with a heavy concentration of post-war walk-up apartments held by investors.',
        'housing_era'   => 'Post-war and 60s-70s walk-up apartments',
        'neighborhoods' => array( 'South Coogee', 'Pagewood', 'Malabar', 'Kingsford' ),
        'lat'           => -33.95,
        'lng'           => 151.2372,
    ),
    'canterbury' => array(
        'name'          => 'Canterbury',
        'postcode'      => '2193',
        'region'        => 'Inner West',
        'council'       => 'Canterbury-Bankstown Council',
        'distance_km'   => 11,
        'description'   => 'Inner south-west suburb of interwar brick homes and post-war flats with a large rental market.',
        'housing_era'   => 'Interwar brick homes and post-war flats',
        'neighborhoods' => array( 'Campsie', 'Hurlstone Park', 'Ashbury', 'Belfield' ),
        'lat'           => -33.911,
        'lng'           => 151.118,
    ),
    'earlwood' => array(
        'name'          => 'Earlwood',
        'postcode'      => '2206',
        'region'        => 'Inner West',
        'council'       => 'Canterbury-Bankstown Council',
        'distance_km'   => 10,
        'description'   => 'Established inner south-west area of interwar and post-war brick homes, many still with their original bathrooms.',
        'housing_era'   => 'Interwar and post-war brick homes',
        'neighborhoods' => array( 'Clemton Park', 'Undercliffe', 'Turrella', 'Bardwell Park' ),
        'lat'           => -33.9241,
        'lng'           => 151.1245,
    ),
    'bexley' => array(
        'name'          => 'Bexley',
        'postcode'      => '2207',
        'region'        => 'Southern Sydney',
        'council'       => 'Bayside Council',
        'distance_km'   => 13,
        'description'   => 'Southern suburb of interwar homes and 60s-70s unit blocks, heavily tenanted and turning over regularly.',
        'housing_era'   => 'Interwar homes and 60s-70s units',
        'neighborhoods' => array( 'Bexley North', 'Kingsgrove', 'Rockdale', 'Bardwell Valley' ),
        'lat'           => -33.9506,
        'lng'           => 151.125,
    ),
    'mortdale' => array(
        'name'          => 'Mortdale',
        'postcode'      => '2223',
        'region'        => 'Southern Sydney',
        'council'       => 'Georges River Council',
        'distance_km'   => 18,
        'description'   => 'Southern rail suburb of post-war brick homes and walk-up flats held long term by owners and investors.',
        'housing_era'   => 'Post-war brick homes and walk-up flats',
        'neighborhoods' => array( 'Penshurst', 'Oatley', 'Peakhurst', 'Hurstville Grove' ),
        'lat'           => -33.97,
        'lng'           => 151.078,
    ),
    'villawood' => array(
        'name'          => 'Villawood',
        'postcode'      => '2163',
        'region'        => 'South West Sydney',
        'council'       => 'Fairfield City Council',
        'distance_km'   => 26,
        'description'   => 'South-west suburb of post-war and former public housing stock where bathrooms are well past their original finish.',
        'housing_era'   => 'Post-war brick and former public housing',
        'neighborhoods' => array( 'Carramar', 'Lansdowne', 'Chester Hill', 'Fairfield East' ),
        'lat'           => -33.872,
        'lng'           => 150.976,
    ),
    'warwick-farm' => array(
        'name'          => 'Warwick Farm',
        'postcode'      => '2170',
        'region'        => 'South West Sydney',
        'council'       => 'Liverpool City Council',
        'distance_km'   => 31,
        'description'   => 'South-west suburb beside the racecourse with a high rental share and mostly post-war housing.',
        'housing_era'   => 'Post-war homes and 70s-80s units',
        'neighborhoods' => array( 'Liverpool', 'Chipping Norton', 'Lansvale', 'Casula' ),
        'lat'           => -33.913,
        'lng'           => 150.937,
    ),
    'casula' => array(
        'name'          => 'Casula',
        'postcode'      => '2170',
        'region'        => 'South West Sydney',
        'council'       => 'Liverpool City Council',
        'distance_km'   => 33,
        'description'   => 'South-west suburb built out from the 70s through the 90s, with bathrooms now at the age where they date a house.',
        'housing_era'   => '70s-90s brick family homes',
        'neighborhoods' => array( 'Liverpool', 'Prestons', 'Glenfield', 'Hammondville' ),
        'lat'           => -33.948,
        'lng'           => 150.902,
    ),
    'austral' => array(
        'name'          => 'Austral',
        'postcode'      => '2179',
        'region'        => 'South West Sydney',
        'council'       => 'Liverpool City Council',
        'distance_km'   => 41,
        'description'   => 'South-west growth area mixing older acreage homes with new estates, so the work splits between tired bathrooms and rental refreshes.',
        'housing_era'   => 'Older acreage homes alongside new estates',
        'neighborhoods' => array( 'Leppington', 'Edmondson Park', 'Bringelly', 'Rossmore' ),
        'lat'           => -33.927,
        'lng'           => 150.808,
    ),
    'camden' => array(
        'name'          => 'Camden',
        'postcode'      => '2570',
        'region'        => 'Macarthur',
        'council'       => 'Camden Council',
        'distance_km'   => 56,
        'description'   => 'Historic Macarthur town where older cottages sit alongside newer estates, and heritage homes are awkward to renovate but straightforward to resurface.',
        'housing_era'   => 'Heritage cottages and 80s-2000s homes',
        'neighborhoods' => array( 'Elderslie', 'Narellan', 'Currans Hill', 'Mount Annan' ),
        'lat'           => -34.0546,
        'lng'           => 150.697,
    ),
    'elderslie' => array(
        'name'          => 'Elderslie',
        'postcode'      => '2570',
        'region'        => 'Macarthur',
        'council'       => 'Camden Council',
        'distance_km'   => 54,
        'description'   => 'Macarthur suburb built through the 90s and 2000s, where bathrooms are dated rather than damaged.',
        'housing_era'   => '90s-2000s brick family homes',
        'neighborhoods' => array( 'Camden', 'Narellan', 'Harrington Park', 'Spring Farm' ),
        'lat'           => -34.0455,
        'lng'           => 150.716,
    ),
    'narellan' => array(
        'name'          => 'Narellan',
        'postcode'      => '2567',
        'region'        => 'Macarthur',
        'council'       => 'Camden Council',
        'distance_km'   => 52,
        'description'   => 'Macarthur centre of 90s and 2000s housing with a growing rental market and plenty of dated but sound bathrooms.',
        'housing_era'   => '90s-2000s project homes',
        'neighborhoods' => array( 'Currans Hill', 'Harrington Park', 'Mount Annan', 'Smeaton Grange' ),
        'lat'           => -34.04,
        'lng'           => 150.739,
    ),
    'gregory-hills' => array(
        'name'          => 'Gregory Hills',
        'postcode'      => '2557',
        'region'        => 'Macarthur',
        'council'       => 'Camden Council',
        'distance_km'   => 50,
        'description'   => 'New Macarthur estate where the work is mostly rental turnarounds and colour changes rather than age-related wear.',
        'housing_era'   => '2010s estate homes',
        'neighborhoods' => array( 'Gledswood Hills', 'Oran Park', 'Harrington Park', 'Smeaton Grange' ),
        'lat'           => -34.0,
        'lng'           => 150.769,
    ),
    'seven-hills' => array(
        'name'          => 'Seven Hills',
        'postcode'      => '2147',
        'region'        => 'Western Sydney',
        'council'       => 'Blacktown City Council',
        'distance_km'   => 32,
        'description'   => 'Western suburb of post-war and 70s homes, heavily investor-held and re-let regularly.',
        'housing_era'   => 'Post-war and 70s brick homes',
        'neighborhoods' => array( 'Blacktown', 'Toongabbie', 'Kings Langley', 'Lalor Park' ),
        'lat'           => -33.774,
        'lng'           => 150.937,
    ),
    'rooty-hill' => array(
        'name'          => 'Rooty Hill',
        'postcode'      => '2766',
        'region'        => 'Western Sydney',
        'council'       => 'Blacktown City Council',
        'distance_km'   => 40,
        'description'   => 'Western suburb of post-war and 70s-80s housing where original bathrooms are the norm rather than the exception.',
        'housing_era'   => 'Post-war and 70s-80s brick homes',
        'neighborhoods' => array( 'Mount Druitt', 'Doonside', 'Plumpton', 'Minchinbury' ),
        'lat'           => -33.771,
        'lng'           => 150.839,
    ),
    'mount-druitt' => array(
        'name'          => 'Mount Druitt',
        'postcode'      => '2770',
        'region'        => 'Western Sydney',
        'council'       => 'Blacktown City Council',
        'distance_km'   => 44,
        'description'   => 'Western centre with extensive 70s and 80s housing, much of it tenanted, where cost-effective bathroom updates matter most.',
        'housing_era'   => '70s-80s brick homes and former public housing',
        'neighborhoods' => array( 'Rooty Hill', 'Whalan', 'Bidwill', 'Tregear' ),
        'lat'           => -33.769,
        'lng'           => 150.818,
    ),
    'wetherill-park' => array(
        'name'          => 'Wetherill Park',
        'postcode'      => '2164',
        'region'        => 'Western Sydney',
        'council'       => 'Fairfield City Council',
        'distance_km'   => 33,
        'description'   => 'Western suburb of 70s and 80s family homes bordering the industrial estate, largely owner-occupied and long held.',
        'housing_era'   => '70s-80s brick family homes',
        'neighborhoods' => array( 'Prairiewood', 'Bossley Park', 'Greystanes', 'Smithfield' ),
        'lat'           => -33.848,
        'lng'           => 150.906,
    ),
    'glenmore-park' => array(
        'name'          => 'Glenmore Park',
        'postcode'      => '2745',
        'region'        => 'Western Sydney',
        'council'       => 'Penrith City Council',
        'distance_km'   => 52,
        'description'   => 'Large 90s Penrith estate now at the age where original bathrooms look dated even though they are structurally sound.',
        'housing_era'   => '90s estate homes',
        'neighborhoods' => array( 'Penrith', 'Regentville', 'Mulgoa', 'Jamisontown' ),
        'lat'           => -33.786,
        'lng'           => 150.669,
    ),
    'windsor' => array(
        'name'          => 'Windsor',
        'postcode'      => '2756',
        'region'        => 'Hawkesbury',
        'council'       => 'Hawkesbury City Council',
        'distance_km'   => 56,
        'description'   => 'Hawkesbury town with heritage cottages and post-war homes, where heritage constraints make resurfacing far simpler than replacing.',
        'housing_era'   => 'Heritage cottages and post-war brick homes',
        'neighborhoods' => array( 'South Windsor', 'Richmond', 'McGraths Hill', 'Bligh Park' ),
        'lat'           => -33.61,
        'lng'           => 150.818,
    ),
    'baulkham-hills' => array(
        'name'          => 'Baulkham Hills',
        'postcode'      => '2153',
        'region'        => 'The Hills District',
        'council'       => 'The Hills Shire Council',
        'distance_km'   => 30,
        'description'   => 'Hills suburb of 70s-90s family homes where bathrooms are original and owners tend to stay put and update.',
        'housing_era'   => '70s-90s brick family homes',
        'neighborhoods' => array( 'Winston Hills', 'Northmead', 'Castle Hill', 'Bella Vista' ),
        'lat'           => -33.761,
        'lng'           => 150.993,
    ),
    'bella-vista' => array(
        'name'          => 'Bella Vista',
        'postcode'      => '2153',
        'region'        => 'The Hills District',
        'council'       => 'The Hills Shire Council',
        'distance_km'   => 34,
        'description'   => 'Newer Hills suburb where the work is largely colour updates and rental turnarounds rather than age-related damage.',
        'housing_era'   => '2000s estate homes and townhouses',
        'neighborhoods' => array( 'Norwest', 'Kellyville', 'Glenwood', 'Baulkham Hills' ),
        'lat'           => -33.737,
        'lng'           => 150.944,
    ),
    'pymble' => array(
        'name'          => 'Pymble',
        'postcode'      => '2073',
        'region'        => 'Upper North Shore',
        'council'       => 'Ku-ring-gai Council',
        'distance_km'   => 18,
        'description'   => 'Upper North Shore suburb of large interwar and post-war homes, often with two or three bathrooms all of the same era.',
        'housing_era'   => 'Interwar and post-war homes on large blocks',
        'neighborhoods' => array( 'Gordon', 'St Ives', 'Turramurra', 'West Pymble' ),
        'lat'           => -33.743,
        'lng'           => 151.143,
    ),
    'willoughby' => array(
        'name'          => 'Willoughby',
        'postcode'      => '2068',
        'region'        => 'Lower North Shore',
        'council'       => 'Willoughby City Council',
        'distance_km'   => 8,
        'description'   => 'Lower North Shore suburb of Federation and interwar homes alongside 60s-70s unit blocks.',
        'housing_era'   => 'Federation and interwar homes with 60s-70s units',
        'neighborhoods' => array( 'Naremburn', 'Artarmon', 'Northbridge', 'Castlecrag' ),
        'lat'           => -33.802,
        'lng'           => 151.198,
    ),
    'collaroy' => array(
        'name'          => 'Collaroy',
        'postcode'      => '2097',
        'region'        => 'Northern Beaches',
        'council'       => 'Northern Beaches Council',
        'distance_km'   => 21,
        'description'   => 'Northern Beaches suburb where coastal exposure is hard on finishes and much of the stock is older walk-up apartments.',
        'housing_era'   => '60s-80s beachside walk-ups and cottages',
        'neighborhoods' => array( 'Narrabeen', 'Dee Why', 'Cromer', 'Wheeler Heights' ),
        'lat'           => -33.735,
        'lng'           => 151.302,
    ),
    'north-curl-curl' => array(
        'name'          => 'North Curl Curl',
        'postcode'      => '2099',
        'region'        => 'Northern Beaches',
        'council'       => 'Northern Beaches Council',
        'distance_km'   => 18,
        'description'   => 'Beachside pocket of post-war homes and small unit blocks where salt air shortens the life of a bathroom finish.',
        'housing_era'   => 'Post-war beachside homes and small blocks',
        'neighborhoods' => array( 'Curl Curl', 'Freshwater', 'Dee Why', 'Queenscliff' ),
        'lat'           => -33.766,
        'lng'           => 151.296,
    ),
    'elanora-heights' => array(
        'name'          => 'Elanora Heights',
        'postcode'      => '2101',
        'region'        => 'Northern Beaches',
        'council'       => 'Northern Beaches Council',
        'distance_km'   => 25,
        'description'   => 'Northern Beaches suburb of 70s and 80s split-level homes, most still with their original bathrooms.',
        'housing_era'   => '70s-80s split-level homes',
        'neighborhoods' => array( 'Ingleside', 'Narrabeen', 'Warriewood', 'Mona Vale' ),
        'lat'           => -33.69,
        'lng'           => 151.283,
    ),
    'gosford' => array(
        'name'          => 'Gosford',
        'postcode'      => '2250',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 76,
        'description'   => 'Central Coast centre with a large stock of older units and post-war homes, and a strong rental market.',
        'housing_era'   => 'Post-war homes and 70s-80s units',
        'neighborhoods' => array( 'East Gosford', 'West Gosford', 'Point Clare', 'Springfield' ),
        'lat'           => -33.427,
        'lng'           => 151.341,
    ),
    'umina-beach' => array(
        'name'          => 'Umina Beach',
        'postcode'      => '2257',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 65,
        'description'   => 'Central Coast beach suburb of post-war cottages and holiday homes where salt air and rental turnover both take a toll.',
        'housing_era'   => 'Post-war beach cottages and holiday units',
        'neighborhoods' => array( 'Woy Woy', 'Ettalong Beach', 'Booker Bay', 'Blackwall' ),
        'lat'           => -33.523,
        'lng'           => 151.312,
    ),
    'toukley' => array(
        'name'          => 'Toukley',
        'postcode'      => '2263',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 92,
        'description'   => 'Northern Central Coast town of post-war homes and older units, largely retiree-owned and long held.',
        'housing_era'   => 'Post-war homes and older units',
        'neighborhoods' => array( 'Norah Head', 'Budgewoi', 'Noraville', 'Canton Beach' ),
        'lat'           => -33.261,
        'lng'           => 151.541,
    ),
    'berkeley-vale' => array(
        'name'          => 'Berkeley Vale',
        'postcode'      => '2261',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 84,
        'description'   => 'Central Coast suburb of 70s and 80s brick homes where bathrooms are original to the build.',
        'housing_era'   => '70s-80s brick family homes',
        'neighborhoods' => array( 'Bateau Bay', 'Tumbi Umbi', 'Chittaway Bay', 'Killarney Vale' ),
        'lat'           => -33.36,
        'lng'           => 151.437,
    ),
    'avoca-beach' => array(
        'name'          => 'Avoca Beach',
        'postcode'      => '2251',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 78,
        'description'   => 'Central Coast beach suburb with a mix of older cottages and holiday rentals, both exposed to salt air.',
        'housing_era'   => 'Beach cottages and holiday rentals',
        'neighborhoods' => array( 'Copacabana', 'Terrigal', 'North Avoca', 'MacMasters Beach' ),
        'lat'           => -33.468,
        'lng'           => 151.434,
    ),
    'hamlyn-terrace' => array(
        'name'          => 'Hamlyn Terrace',
        'postcode'      => '2259',
        'region'        => 'Central Coast',
        'council'       => 'Central Coast Council',
        'distance_km'   => 88,
        'description'   => 'Newer Central Coast estate where the work is mostly rental turnarounds and colour changes.',
        'housing_era'   => '2000s-2010s estate homes',
        'neighborhoods' => array( 'Woongarrah', 'Wadalba', 'Warnervale', 'Blue Haven' ),
        'lat'           => -33.247,
        'lng'           => 151.467,
    ),
    'north-wollongong' => array(
        'name'          => 'North Wollongong',
        'postcode'      => '2500',
        'region'        => 'Illawarra',
        'council'       => 'Wollongong City Council',
        'distance_km'   => 82,
        'description'   => 'Illawarra coastal suburb close to the university with a heavy student-rental share and older unit stock.',
        'housing_era'   => '60s-80s units and post-war homes',
        'neighborhoods' => array( 'Fairy Meadow', 'Keiraville', 'Gwynneville', 'Towradgi' ),
        'lat'           => -34.408,
        'lng'           => 150.899,
    ),
    'fairy-meadow' => array(
        'name'          => 'Fairy Meadow',
        'postcode'      => '2519',
        'region'        => 'Illawarra',
        'council'       => 'Wollongong City Council',
        'distance_km'   => 80,
        'description'   => 'Illawarra suburb of post-war homes and older units, with a steady rental market near the university.',
        'housing_era'   => 'Post-war homes and 70s-80s units',
        'neighborhoods' => array( 'North Wollongong', 'Balgownie', 'Towradgi', 'Mount Ousley' ),
        'lat'           => -34.39,
        'lng'           => 150.889,
    ),
    'shellharbour' => array(
        'name'          => 'Shellharbour',
        'postcode'      => '2529',
        'region'        => 'Illawarra',
        'council'       => 'Shellharbour City Council',
        'distance_km'   => 99,
        'description'   => 'Illawarra coastal town mixing older beachside cottages with newer estates, both exposed to salt air.',
        'housing_era'   => 'Beachside cottages and 90s-2000s estates',
        'neighborhoods' => array( 'Shell Cove', 'Barrack Heights', 'Warilla', 'Flinders' ),
        'lat'           => -34.581,
        'lng'           => 150.867,
    ),
    'albion-park' => array(
        'name'          => 'Albion Park',
        'postcode'      => '2527',
        'region'        => 'Illawarra',
        'council'       => 'Shellharbour City Council',
        'distance_km'   => 96,
        'description'   => 'Illawarra town built out through the 80s and 90s, where bathrooms are dated rather than damaged.',
        'housing_era'   => '80s-90s brick family homes',
        'neighborhoods' => array( 'Albion Park Rail', 'Oak Flats', 'Tullimbar', 'Calderwood' ),
        'lat'           => -34.571,
        'lng'           => 150.777,
    ),
);
